import os
import logging
from datetime import date

import requests
from instagrapi import Client as InstaClient

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s"
)
log = logging.getLogger(__name__)

NOTION_TOKEN = os.environ["NOTION_TOKEN"]
NOTION_DATABASE_ID = os.environ["NOTION_DATABASE_ID"]
INSTAGRAM_USERNAME = os.environ["INSTAGRAM_USERNAME"]
INSTAGRAM_PASSWORD = os.environ["INSTAGRAM_PASSWORD"]
INSTAGRAM_SESSION = os.environ["INSTAGRAM_SESSION"]   # JSON from generate_ig_session.py
LINKEDIN_LI_AT = os.environ["LINKEDIN_LI_AT"]         # browser cookie
LINKEDIN_JSESSIONID = os.environ["LINKEDIN_JSESSIONID"]  # browser cookie

NOTION_HEADERS = {
    "Authorization": f"Bearer {NOTION_TOKEN}",
    "Notion-Version": "2022-06-28",
    "Content-Type": "application/json",
}


# ---------- Notion helpers ----------

def get_existing_urls():
    """Return the set of URLs already in the Notion database."""
    endpoint = f"https://api.notion.com/v1/databases/{NOTION_DATABASE_ID}/query"
    existing = set()
    cursor = None

    while True:
        body = {"page_size": 100}
        if cursor:
            body["start_cursor"] = cursor
        resp = requests.post(endpoint, headers=NOTION_HEADERS, json=body)
        resp.raise_for_status()
        data = resp.json()

        for page in data.get("results", []):
            url_val = page.get("properties", {}).get("URL", {}).get("url")
            if url_val:
                existing.add(url_val)

        if not data.get("has_more"):
            break
        cursor = data.get("next_cursor")
        if not cursor:
            break  # has_more=true but no cursor — avoid infinite loop

    log.info(f"Notion: {len(existing)} existing URLs")
    return existing


def save_to_notion(item):
    """Create a new row in the Notion database for a saved item."""
    title = (item.get("title") or "").strip()[:200] or item["url"]
    body = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "properties": {
            "Title": {"title": [{"text": {"content": title}}]},
            "URL": {"url": item["url"]},
            "Source": {"select": {"name": item["source"]}},
            "Status": {"select": {"name": "Unread"}},
            "Date Saved": {"date": {"start": date.today().isoformat()}},
        },
    }
    resp = requests.post(
        "https://api.notion.com/v1/pages", headers=NOTION_HEADERS, json=body
    )
    resp.raise_for_status()


# ---------- Instagram ----------

def get_instagram_saves():
    log.info("Instagram: fetching saved posts...")
    cl = InstaClient()

    # Load the mobile session generated by generate_ig_session.py.
    # This is a proper instagrapi mobile-API session, NOT a web browser cookie.
    # login_by_sessionid() is intentionally NOT used here — web browser sessionid
    # is rejected by the mobile API with HTTP 467.
    session_file = "/tmp/ig_session.json"
    with open(session_file, "w") as f:
        f.write(INSTAGRAM_SESSION)

    cl.load_settings(session_file)
    cl.login(INSTAGRAM_USERNAME, INSTAGRAM_PASSWORD)
    log.info("Instagram: logged in via saved mobile session")

    # amount=0 fetches all pages, not just the first batch of ~50
    saved = cl.user_saved_medias(amount=0)
    log.info(f"Instagram: {len(saved)} saved posts found")

    results = []
    for media in saved:
        if not media.code:
            log.warning(f"Instagram: media {media.pk} has no shortcode, skipping")
            continue
        caption = (media.caption_text or "").replace("\n", " ")
        results.append({
            "url": f"https://www.instagram.com/p/{media.code}/",
            "title": caption[:150],
            "source": "Instagram",
        })
    return results


# ---------- LinkedIn ----------

def get_linkedin_saves():
    log.info("LinkedIn: fetching saved posts...")

    # Strip quotes from env var in case the user copied it with surrounding quotes.
    # The JSESSIONID cookie must be sent with quotes as part of its value ("ajax:xxx").
    # The csrf-token header must be sent without quotes.
    csrf = LINKEDIN_JSESSIONID.strip('"')

    cookies = {
        "li_at": LINKEDIN_LI_AT,
        "JSESSIONID": f'"{csrf}"',
    }
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        "Accept": "application/vnd.linkedin.normalized+json+2.1",
        "csrf-token": csrf,
        "x-restli-protocol-version": "2.0.0",
        "x-li-lang": "en_US",
        "Referer": "https://www.linkedin.com/feed/",
        "x-li-track": (
            '{"clientVersion":"1.13.1","mpVersion":"1.13.1","osName":"web",'
            '"timezoneOffset":0,"timezone":"UTC","appType":"VOYAGER",'
            '"displayDensity":2,"displayWidth":1920,"displayHeight":1080}'
        ),
    }

    # Pass cookies directly (not via Session.cookies.set) to avoid domain-matching
    # issues in requests' cookie jar silently dropping them.
    resp = requests.get(
        "https://www.linkedin.com/voyager/api/contentcollection/updatesV2",
        params={"q": "savedItems", "count": 100, "start": 0},
        headers=headers,
        cookies=cookies,
    )

    log.info(f"LinkedIn: status = {resp.status_code}")

    if resp.status_code in (401, 403):
        raise RuntimeError(
            f"LinkedIn auth failure ({resp.status_code}) — "
            "refresh LINKEDIN_LI_AT and LINKEDIN_JSESSIONID (see SETUP.md Section B)"
        )
    if resp.status_code != 200:
        raise RuntimeError(
            f"LinkedIn unexpected status {resp.status_code}: {resp.text[:300]}"
        )

    data = resp.json()
    elements = data.get("elements", [])
    log.info(f"LinkedIn: {len(elements)} saved items found")

    if elements:
        log.info(f"LinkedIn: first element keys = {list(elements[0].keys())}")

    results = []
    for el in elements:
        url = (
            el.get("entityUrl")
            or el.get("navigationUrl")
            or (el.get("value") or {}).get("entityUrl")
            or (el.get("savedContent") or {}).get("canonicalUrl")
            or ""
        )
        title_field = el.get("title", "")
        title = (
            title_field.get("text", "") if isinstance(title_field, dict)
            else str(title_field)
        )
        if url:
            results.append({"url": url, "title": title[:150], "source": "LinkedIn"})
        else:
            log.warning(f"LinkedIn: no URL in element — keys: {list(el.keys())}")

    return results


# ---------- Main ----------

def main():
    # Abort rather than risk mass re-duplication if Notion is unreachable
    try:
        existing_urls = get_existing_urls()
    except Exception as e:
        log.critical(f"Cannot fetch existing Notion URLs — aborting to avoid duplicates: {e}")
        raise SystemExit(1)

    all_saves = []
    instagram_ok = False
    linkedin_ok = False

    try:
        all_saves += get_instagram_saves()
        instagram_ok = True
    except Exception as e:
        log.error(f"Instagram sync failed: {e}")

    try:
        all_saves += get_linkedin_saves()
        linkedin_ok = True
    except Exception as e:
        log.error(f"LinkedIn sync failed: {e}")

    if not instagram_ok and not linkedin_ok:
        log.critical("Both sources failed — marking workflow as failed")
        raise SystemExit(1)

    new_items = [item for item in all_saves if item["url"] not in existing_urls]
    log.info(f"Sync: {len(new_items)} new items (out of {len(all_saves)} total fetched)")

    synced = 0
    for item in new_items:
        try:
            save_to_notion(item)
            log.info(f"  + {item['source']}: {item['url']}")
            synced += 1
        except Exception as e:
            log.error(f"  ! Failed to save {item['url']}: {e}")

    log.info(f"Sync complete: {synced} new items added to Notion")


if __name__ == "__main__":
    main()
